#!/usr/bin/env python3
"""
AUTO-SAVE SESSION TRANSCRIPT
Copies current OpenClaw session JSONL to memory/ with metadata header
Runs via cron every 6 hours (4x/day = ~$0.36/day)
"""

import os
import glob
import json
from datetime import datetime, timezone

MEMORY_DIR = "/home/agent/workspace/memory"
SESSIONS_DIR = os.path.expanduser("~/.openclaw/agents/main/sessions")
os.makedirs(MEMORY_DIR, exist_ok=True)

def find_latest_session():
    """Find the most recently modified session JSONL file"""
    pattern = os.path.join(SESSIONS_DIR, "*.jsonl")
    files = glob.glob(pattern)
    
    if not files:
        return None
    
    # Sort by modification time, newest first
    files.sort(key=os.path.getmtime, reverse=True)
    return files[0]

def export_session(jsonl_path):
    """Copy JSONL file to memory/ with metadata header"""
    try:
        timestamp = datetime.now(timezone.utc).strftime('%Y-%m-%d_%H%M')
        output_file = f"{MEMORY_DIR}/session_{timestamp}_auto.jsonl"
        
        # Read first and last few lines to get metadata
        with open(jsonl_path, 'r') as f:
            lines = f.readlines()
        
        msg_count = len(lines)
        file_size = os.path.getsize(jsonl_path)
        
        # Copy file
        import shutil
        shutil.copy2(jsonl_path, output_file)
        
        print(f"✓ Saved {msg_count} messages ({file_size:,} bytes) to {output_file}")
        
        # Also create a summary markdown file
        summary_file = f"{MEMORY_DIR}/session_{timestamp}_summary.md"
        
        # Parse first message for context
        first_msg = None
        last_msg = None
        if lines:
            try:
                first_msg = json.loads(lines[0])
                last_msg = json.loads(lines[-1])
            except:
                pass
        
        content = f"""# Session Summary - {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}

**Source**: `{jsonl_path}`  
**Messages**: {msg_count}  
**Size**: {file_size:,} bytes  
**Full transcript**: `session_{timestamp}_auto.jsonl`

---

## First Message
{json.dumps(first_msg, indent=2)[:500] if first_msg else "N/A"}

## Last Message  
{json.dumps(last_msg, indent=2)[:500] if last_msg else "N/A"}

---

*Auto-generated by Recon session exporter*
"""
        
        with open(summary_file, 'w') as f:
            f.write(content)
        
        print(f"✓ Summary saved to {summary_file}")
        return True
        
    except Exception as e:
        print(f"✗ Error exporting session: {e}")
        import traceback
        traceback.print_exc()
        return False

if __name__ == "__main__":
    print(f"[{datetime.now(timezone.utc).isoformat()}] Auto-save session started")
    
    latest = find_latest_session()
    if latest:
        print(f"Latest session: {latest}")
        success = export_session(latest)
        if success:
            print("Auto-save complete")
        else:
            print("Auto-save failed")
    else:
        print("No session files found")
